# Generated by Django 3.2 on 2021-07-21 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
