# Generated by Django 3.2 on 2021-07-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_alter_song_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_link',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
